server:
  port: 8761
eureka:
  instance:
    hostname: euraka-server #eureka实例的主机名
  client:
    register-with-eureka: false  #不将自身注册到euraka上
    fetch-registry: false  #不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: registercenter
  cloud:
    loadbalancer:
      ribbon:
        enabled: false