server:
  port: 8200

spring:
  application:
    name: consumer-user
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务ip地址
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
